/**
 * Princes' Coffee blog articles — sourced verbatim from princes.sa/blog.
 *
 * Line markers in `parts`:
 *   - "## " -> <h2>
 *   - "### " -> <h3>
 *   - "- " -> <li>
 *   - "@link url|label" -> <a href="url">label</a>
 */

export interface Article {
  slug: string;
  img: string;
  kicker: string;
  kickerEn: string;
  title: string;
  titleEn: string;
  parts: string[];
  partsEn: string[];
}

export const articles: Article[] = [
  {
    slug: "saudi-coffee",
    img: "/brand/blog/saudi-coffee.jpg",
    kicker: "ثقافتنا",
    kickerEn: "Our Culture",
    title: "أصل وتاريخ القهوة السعودية",
    titleEn: "The Origin and History of Saudi Coffee",
    parts: [
      "القهوة هي مشروب شعبي في العالم العربي، وتحتل مكانة خاصة في المملكة العربية السعودية. تشتهر القهوة السعودية بنكهتها الفريدة والمميزة، والتي تعكس تاريخ وثقافة المنطقة.",
      "تاريخ القهوة في السعودية يعود إلى العصور الوسطى، حيث كانت القهوة تستخدم بشكل رئيسي في الأندلس واليمن. ومع مرور الوقت، انتقلت ثقافة القهوة إلى مناطق أخرى في العالم العربي، بما في ذلك المملكة العربية السعودية.",
      "يعتقد البعض أن القهوة وصلت إلى المملكة العربية السعودية في القرن السادس عشر الميلادي، عندما قام التجار العثمانيون بتجارة القهوة مع المملكة. وفي ذلك الوقت، كانت مدينة جدة هي المركز الرئيسي لتجارة القهوة في المملكة العربية السعودية.",
      "ومع مرور الوقت، انتشرت ثقافة شرب القهوة في المملكة العربية السعودية، وأصبحت مناسبات شرب القهوة جزءًا من التقاليد الاجتماعية. وتختلف طريقة تحضير القهوة في المملكة العربية السعودية عن طرق تحضير القهوة في مناطق أخرى، حيث يتم استخدام مواد مختلفة لتحسين النكهة، مثل الهيل والزعفرانوالمسمار.",
      "تعد القهوة السعودية من أفضل أنواع القهوة في العالم، ويتم تصديرها إلى الكثير من الدول الأخرى. وتتميز القهوة السعودية بنكهتها القوية والمميزة، والتي تعكس تاريخ وثقافة المنطقة.",
      "## اعتماد القهوة السعودية كمشروب رسمي:",
      "وفي عام 2013، أعلنت وزارة التجارة والصناعة السعودية عن اعتماد “القهوة السعودية” كمشروب رسمي في المملكة العربية السعودية. ويهدف هذا الإعلان إلى تعزيز القهوة السعودية وتعزيز مكانتها كمشروب وطني.",
      "ويعكس هذا الإعلان الدور المهم الذي تلعبه القهوة في الثقافة السعودية، ويعزز اعتراف الحكومة بأهمية القهوة في المجتمع السعودي.",
      "ويعد هذا الاعتماد إشارة إلى جودة وموثوقية القهوة السعودية، ويضيف لمسة من الفخامة والرفاهية للمشروب. ويمكن لمثل هذه الاعتمادات أن تزيد من الإقبال على القهوة السعودية وتحفيز الاستثمار في صناعة القهوة في المملكة.",
      "بالإضافة إلى ذلك، تعمل الحكومة السعودية على دعم صناعة القهوة المحلية وتشجيع المزارعين على زراعة حبوب القهوة وتحسين جودتها، مما يدفع بصناعة القهوة السعودية للأمام.",
      "ومن خلال اعتماد “القهوة السعودية” كمشروب رسمي، فإن الحكومة السعودية تعزز القهوة السعودية كعلامة تجارية وطنية، وتعزز مكانتها على الساحة الدولية.",
      "## أخيرًا:",
      "في الختام، تعد القهوة السعودية من الثروات الوطنية الهامة في المملكة العربية السعودية، وتشكل جزءًا لا يتجزأ من التراث الثقافي للمنطقة. وبفضل الجودة العالية للقهوة السعودية، فإن الطلب عليها يزداد يومًا بعد يوم.",
    ],
    partsEn: [
      "Coffee is a popular beverage in the Arab world, particularly in the Kingdom of Saudi Arabia, where it holds a special place. Saudi coffee is known for its unique and distinct flavor that reflects the history and culture of the region.",
      "The history of coffee in Saudi Arabia dates back to the Middle Ages, where it was primarily used in Andalusia and Yemen. Over time, the coffee culture spread to other regions in the Arab world, including the Kingdom of Saudi Arabia.",
      "Some believe that coffee arrived in the Kingdom of Saudi Arabia in the 16th century, when Ottoman traders traded coffee with the Kingdom. At that time, Jeddah was the main center for coffee trade in the Kingdom of Saudi Arabia.",
      "As time passed, the coffee drinking culture spread throughout the Kingdom of Saudi Arabia, and coffee drinking occasions became part of social traditions. The method of preparing coffee in Saudi Arabia differs from other regions, where different ingredients, such as cardamom, saffron, and cloves, are used to enhance the flavor.",
      "Saudi coffee is considered one of the best types of coffee in the world and is exported to many other countries. It is known for its strong and distinctive flavor that reflects the history and culture of the region.",
      "## Adoption of coffee as an official beverage:",
      "In 2013, the Saudi Ministry of Commerce and Industry announced the adoption of “Saudi coffee” as an official beverage in the Kingdom of Saudi Arabia. This announcement aims to promote Saudi coffee and enhance its position as a national beverage.",
      "This adoption reflects the important role that coffee plays in Saudi culture and reinforces the government's recognition of the importance of coffee in Saudi society.",
      "This adoption is a sign of the quality and reliability of Saudi coffee and adds a touch of luxury and sophistication to the beverage. Such adoptions can increase demand for Saudi coffee and stimulate investment in the coffee industry in the Kingdom.",
      "In addition, the Saudi government is working to support the local coffee industry and encourage farmers to cultivate coffee beans and improve their quality, pushing the Saudi coffee industry forward.",
      "By adopting “Saudi coffee” as an official beverage, the Saudi government is promoting Saudi coffee as a national trademark and enhancing its position on the international scene.",
      "## Finally:",
      "In conclusion, Saudi coffee is one of the important national treasures in the Kingdom of Saudi Arabia and is an integral part of the cultural heritage of the region. Thanks to the high quality of Saudi coffee, demand for it is increasing day by day.",
    ],
  },
  {
    slug: "coffee-benefits",
    img: "/brand/blog/benefits.jpg",
    kicker: "صحتك",
    kickerEn: "Your Health",
    title: "فوائد القهوة: أهم ٥ فوائد لتناول القهوة بدون سكر.",
    titleEn: "Benefits of Coffee: Top 5 Benefits of Drinking Coffee without Sugar",
    parts: [
      "للقهوة مزاجها الخاص، واحساسها الفريد باستشعار اللحظة، ولكن يُشاع كثيرًا أنها مُضرة، وهذا ليس صحيح تمامًا هي مضرة حينما تتجاوز الكمية المسموحة ٤٠٠ جرام، بما يعادل ٤ أكواب في اليوم وهي كافيه جدًا، لكن بغض النظر عن تداول أضرارها نحن هنا بصدد ذكر فوائد القهوة، وهنا سنتناول أهم ٥ فوائد لشرب القهوة بدون سكر.",
      "## فوائد القهوة: فوائد شرب القهوة بدون سكر:",
      "### رفع مستوى نشاط الجسم:",
      "تعزز القهوة مستويات الطاقة في الجسم عن طريق تحفيز الجهاز العصبي وذلك بإيقاف المستقبلات الحسية في الدماغ والتي بدورها تساهم برفع نشاط الجسم، كذلك من فوائد القهوة أنها تفرز هرمون الأدرينالين وهو المسؤول عن تحفيز الطاقة في الدماغ.",
      "### خفض مستوى السكر في الدم:",
      "احدى فوائد القهوة بدون سكر أنها تدعم وظائف الكبد وتنشط عملية الأيض مما يجعلها تستهلك السكر في الدم وتخفف مقاومج الأنسولين وهذا ما يساعد في توازن قراءة السكر.",
      "### خسارة الوزن:",
      "لا يصدق الكثير أن من فوائد القهوة خسارة الوزن، لكنها حقيقية جدًا في حال توازن الأكل.",
      "### كيف يكون ذلك؟",
      "بسبب قلة مقاومة الأنسولين ارتفاع نشاط الجسم وهرمون النمو وهذا ما يساعم برفع الخلايا التي تساعد بحرق الدهون.",
      "### تنشيط الدورة الدموية:",
      "فائدة أخرى من فوائد القهوة، حيث تساعد بتحريك الدورة الدموية في الجسم بشكل مثالي فتخفض نسبة الجلطات والسكتات الدماغية، وقد أثببت الدراسات أن الرياضيون الذين يتناولون القهوة قبل التمرين يكون النشاط الرياضي أقوى بـنسبة ١٧٪",
      "### تعزيز قوة الجهاز الهضمي:",
      "أهم فوائد شرب القهوة والتي تلاحظ نتيجتها بشكل فوري هي تحسين الهضم، فما الذي يحدث عند شرب القهوة في المعدة؟",
      "تنشط البكتيريا النافعة في القولون والحركة الدودية في الأمعاء فتفرز عصارة المعدة مما يجعل الهضم سريع وطبيعي.",
      "## ختامًا:",
      "في هذا المقال حاولنا أن نلخص أهم المعلومات لفوائد القهوة بطريقة سلسة وسهلة للفهم والاستيعاب، وندرك جيدًا مدى فائدة القهوة، ولكن ننصح بشربها بدون سكر وكذلك الاعتدال والتوازن في تناولها بدون إفراط.",
      "للمزيد من المعلومات تفضلوا بزيارة رابط وزارة الصحة لصفحة الكافيين:",
      "@link https://www.moh.gov.sa/awarenessplateform/HealthyLifestyle/Pages/Caffeine.aspx|وزارة الصحة — الكافيين",
    ],
    partsEn: [
      "Coffee has its own unique mood and feeling, but it is often thought to be harmful. However, this is not entirely true. Coffee is harmful only when consumed in amounts exceeding 400 grams, which is equivalent to 4 cups per day. Despite the debate about its harmful effects, we are here to discuss the benefits of coffee, specifically the top 5 benefits of drinking coffee without sugar.",
      "## Benefits of coffee: Benefits of drinking coffee without sugar:",
      "### 1. Boosts body activity:",
      "Coffee enhances energy levels in the body by stimulating the nervous system. It does this by blocking sensory receptors in the brain, which in turn contributes to raising body activity. Additionally, one of the benefits of coffee is that it releases adrenaline, which is responsible for stimulating energy in the brain.",
      "### 2. Reduces blood sugar levels:",
      "One of the benefits of coffee without sugar is that it supports liver function and activates the metabolism, which helps consume sugar in the blood and reduces insulin resistance. This helps to balance blood sugar levels.",
      "### 3. Weight loss:",
      "One of the surprising benefits of coffee is weight loss, but it is true when balanced with a healthy diet. Due to the low insulin resistance, body activity and growth hormone increase, which leads to an increase in cells that burn fat.",
      "### 4. Improves blood circulation:",
      "Another benefit of coffee is that it helps to improve blood circulation in the body, which reduces the risk of clots and strokes. Studies have also shown that athletes who drink coffee before exercising have a 17% increase in athletic performance.",
      "### 5. Enhances digestive power:",
      "One of the most noticeable benefits of drinking coffee is improving digestion. What happens when you drink coffee in your stomach? Beneficial bacteria in the colon are stimulated, and intestinal movement is activated, which increases stomach juices and makes digestion fast and natural.",
      "## In conclusion:",
      "In this article we tried to summarize the most important information about the benefits of coffee in an easy-to-understand and digestible way. We realize the benefits of coffee, but we advise drinking it without sugar and with moderation and balance.",
      "For more information, please visit the Ministry of Health's caffeine page at:",
      "@link https://www.moh.gov.sa/awarenessplateform/HealthyLifestyle/Pages/Caffeine.aspx|Ministry of Health — Caffeine",
    ],
  },
  {
    slug: "coffee-culture",
    img: "/brand/blog/culture.jpg",
    kicker: "ثقافتنا",
    kickerEn: "Our Culture",
    title: "القهوة والحياة الثقافية",
    titleEn: "Coffee and Cultural Life",
    parts: [
      "باعتبار القهوة المشروب الأكثر انتشارًا حول العالم، لاتعتبر القهوة مجرد مشروب بل رمزًا للثقافة والإلهام لدى المثقفين والمبدعين والمفكرين، وتجسد قيمة مهمة أثناء الإنتاج الإبداعي والتفكير.",
      "## الثقافة والقهوة: علاقة المثقفين بالقهوة.",
      "يعود ارتباط وعلاقة المثقفين بالقهوة إلى القرن السابع عشر، فمنذ سالف العصر اجتمع المثقفين حول طاولات اجتماعاتهم رفقة فناجينهم لما يُحفزه الكافيين الموجود بالقهوة لعقولهم ولاعتبارها رمزًا للحياة حسب طعمها، فالكثير يشبه مرارة أيامه بمرارة القهوة وحلاوة أيامه بحلاوة القهوة. ومنذ ذلك الحين، انتشرت القهوة في جميع أنحاء العالم، وأصبحت رمزا للتفكير الفلسفي والأدبي والعلمي.",
      "## القهوة والعلاقات الاجتماعية.",
      "لا تغيب القهوة عن المناسبات الاجتماعية في مختلف بلدان العالم، فهي عند البعض رمزًا للضيافة والكرم، وعند الآخر هي مناسبة للاجتماع والحديث، بدءًا من النساء بالحارات اللاتي يجتمعن لتبادل الأخبار ونشرها تحت مسمى شرب القهوة معًا، إلى أصحاب القرارات ومنفذيها، الذين تشهد فناجينهم على مختلف حواراتهم.",
      "كما أن دخولك أو انضمامك لطاولة القهوة يعبر أو يعكس اندماجك داخل مجموعة معينة.",
      "حيث أن القهوة مصدر للتواصل الاجتماعي بين المثقفين، حيث يجتمعون في المقاهي والمتاجر المخصصة للقهوة للتحدث عن الأفكار والأحداث الجارية. وبالإضافة إلى ذلك، فإن القهوة تقدم بيئة مريحة ومريحة للمثقفين للعمل والكتابة والإبداع.",
      "## القهوة والثقافة: علاقة القهوة بالفن والأدب.",
      "ليست القهوة فقط الصديق الدائم والمخلص للفنانين خاصة الشعراء والأدباء، بل هي مصدر إلهام وتشبيه محبذ يستقبله الجميع برحابة صدر لايختلف عليها اثنان، فقد كتب العديد من الشعراء غرلًا بالقهوة ونكهاتها وابدع الكثيرون بوصفها.",
      "ويمكن للمثقفين الاستفادة من القهوة في عملية الكتابة، ومن المؤكد أن المثقفين يعرفون جيدًا قيمة تناول فنجان من القهوة أثناء الكتابة، حيث يمكن للقهوة أن تفتح الذهن لأفكار وآفاق واسعة وتساعد في تجاوز الصعوبات الكتابية.",
      "## أخيرًا:",
      "تعد علاقة المثقفين بالقهوة علاقة وثيقة ومتينة، تمثل لهم إحساسًا بالرخاء والراحة، وتمدهم بالإلهام اللازم للنتاج الإبداعي الذين يعملون عليه، كما يعتبر فنجان القهوة صديقًا ملازمًا لكل فنان وقارئ وأديب، إذ تشرّع له أبوابًا مختلفة من الأفكار الإبداعية والجمالية.",
    ],
    partsEn: [
      "As the most widely consumed beverage in the world, coffee is not just a drink but also a symbol of culture and inspiration for intellectuals, creatives, and thinkers. It embodies an important value during the creative production and thinking process.",
      "## Coffee and Intellectuals: The Relationship between Coffee and Intellectuals",
      "The relationship between intellectuals and coffee dates back to the seventeenth century, where intellectuals gathered around tables with their cups, as the caffeine in coffee stimulated their minds and became a symbol of life according to its taste. Since then, coffee has spread all over the world and has become a symbol of philosophical, literary, and scientific thinking.",
      "## Coffee and Social Relationships",
      "Coffee is present in social events in various countries around the world. For some, it is a symbol of hospitality and generosity, while for others, it is an occasion to meet and talk. Joining a coffee table reflects your integration into a certain group. In addition, coffee provides a source of social communication among intellectuals, where they gather in coffee shops and coffee specialty stores to talk about ideas and current events.",
      "## Coffee and Culture: The Relationship between Coffee and Art and Literature",
      "Coffee is not only a constant and loyal friend to artists, especially poets and writers, but also a source of inspiration and a preferred comparison that everyone welcomes. Many poets have written about their love for coffee, its flavors, and its description. Intellectuals can benefit from coffee in the writing process, as they know well the value of having a cup of coffee while writing.",
      "## In conclusion:",
      "The relationship between intellectuals and coffee is a close and strong one, which provides them with a sense of comfort and relaxation and provides the necessary inspiration for their creative outputs. The cup of coffee is also a constant friend to every artist, reader, and writer, opening different doors of creative and aesthetic ideas.",
    ],
  },
  {
    slug: "coffee-history",
    img: "/brand/blog/history.jpg",
    kicker: "حكاية البن",
    kickerEn: "The Bean Story",
    title: "تاريخ القهوة: أصل القهوة واكتشافها",
    titleEn: "Coffee History: Origin and Discovery",
    parts: [
      "## متى تم اكتشاف القهوة؟",
      "رغم كل المقالات العلمية والبحوث بشأن القهوة حتى الآن لم يحدد بدقة تاريخ اكتشافها فهناك من قال منذ القرن الخامس عشر وهناك من قال القرن الحادي عشر وبعضهم يقول انها في القرن التاسع، ولكن رغم اختلافهم في تحديد المدة إلا أن القهوة اكُتشفت منذ القرون الوسطى بشكل عام.",
      "## أين اُكتشفت القهوة لأول مرة؟",
      "عالم القهوة واسع وجميل، وتجارتها مُربحة وهذا ما يجعل الشعوب تختلف حول اكتشافها أول مره كل بلد تعتقد انها الأولى في اكتشاف القهوة.",
      "## اسطورة الماعز:",
      "يُقال إن هناك مزارع في أثيوبيا يمتلك قطيع ماعز وكان يرعاها وذات مره أكلت الماعز من شجرة البن وأصبحت أكثر نشاطًا وحركة من بين القطيع فتتبع مسارها ووجد الشجرة، فقام بتجربة النبتة بنفسه فإذا به يزداد نشاطًا وحيوية، فأخذها للرجال في قريته ووضعوها في ماء وتغير لونه ورائحته أصبحت متميزة وزكية، تذوقوها فأعجبتهم ومن هنا بدأت القهوة وانتشرت.",
      "ورغم الأساطير المختلفة حول أصل القهوة، وتاريخ القهوة، ونشأة القهوة إلا أن العلماء تتبعوا أصل النبتة فوجدوا انها تعود لليمن يُرجح أن أول مره اكتشف فيها البن في اليمن في مينا المخاء.",
      "## أصل القهوة، وانتشارها.",
      "بدأت القهوة من بلاد العرب ومن اليمن في الأديرة الصوفية حيث تساعدهم على الاستيقاظ ليلًا للتعبد، وقد احتكر العرب تجارتها، فلم تكن تحمص القهوة في الأصل، ولكن تم تحميصها وتصديرها حتى لا يمكن زراعتها بعد التحميص، وكانت الفكرة احتكارية في التجارة.",
      "انتشرت القهوة في عصر الدولة العثمانية مع التوسع الجغرافي وصلت لليونان، وملطا، وإيطاليا، واسبانيا، وألمانيا وتركيا وغيرها من بلدان العالم حيث يتم استهلاك يوميًا ٢ مليار كوب قهوة حول العالم.",
      "وفي بداية انتشار القهوة وانتقالها من اليمن للدول المجاورة بعد تجربة القهوة من الناس وتجمعهم حولها، وافتتاح المقاهي قد صدرت عدة فتاوى تُحرم القهوة آنذاك لجهلهم بهذا المشروب باعتقادهم أنه أحد أنواع الخمور حيث يشتق اسم قهوة من الخمر -يقهي- يعني يسد الشهية في اللغة.",
      "ولكن بعد التأكد من الأطباء بخصوص مفعولها تم اباحتها وتطورت القهوة منذ ذلك الحين حتى الآن أصبحت احدى رموز الكرم والمروءة.",
      "## أصل القهوة: القهوة في البلدان العربية:",
      "تعتبر القهوة جزءًا لا يتجزأ من ثقافة البلدان العربية، وهي مشروب شائع يرمز للمروءة والكرم، حيث جاءت القهوة للبدان العربية، ولكن تنوعت أنواع البن وطرق استخلاصه وطريقة تحضيره حيث تشتهر قهوة الجاهلي في الكويت والقهوة التركية في بلاد الشام، كذلك القهوة السعودية تنتشر في البحرين والامارات والسعودية، والقهوة السودانية الغنية بالمذاق المتفرد وتقدم في أكواب صغيرة تسمى “الجاك”، حيث أنها أحد رموز الضيافة السودانية.",
      "انتشرت القهوة وأصبحت تُزرع في أكثر من ٧٠ دولة حيث العالم، بأنواع ونكهات مختلفة وطرق تحميص وتحضير متنوعة، وأصبحت مشروب مفضل وأساسي في أغلب الحضارات والثقافات.",
      "## المقاهي وأصل القهوة:",
      "بعد انتشار القهوة بدأت التجارة بها وتم افتتاح المقاهي في بلاد العرب حيث يجتمع الرجال حولها ويلعبون الشطرنج ويتبادلون أطراف الحديث، فتم التوسع وانتقلت العادة إلى جميع بلاد أوروبا مما ساهمت أوروبا بشكل كبير بنشر القهوة وثقافتها وإيصالها للأمريكيتين، وكل بلد وصلت لها القهوة حضرتها واعدتها وقدمتها بطريقتها حتى أًصبح لكل ثقافة قهوتها الخاصة.",
    ],
    partsEn: [
      "## When was coffee discovered?",
      "Despite all the scientific articles and research on coffee, its discovery date has not been accurately determined yet. Some claim it was discovered in the 15th century, while others believe it was in the 11th century, and some even say it was in the 9th century. However, despite their differences in identifying the period, coffee was generally discovered during the Middle Ages.",
      "## Where was coffee first discovered?",
      "The world of coffee is vast and beautiful, and its trade is profitable, which makes countries differ about the first time coffee was discovered.",
      "## The Legend of the Goat:",
      "It is said that there is a farmer in Ethiopia who owns a herd of goats, and he used to take care of them. One day, the goats ate from the coffee tree and became more active and lively than the rest of the herd. They followed their path and found the tree, so he tried the plant himself, and he felt more active and energetic. He took it to the men in his village, put it in water, and its color changed, and its smell became distinctive and delicious. They tasted it and liked it, and this is how coffee began and spread.",
      "Despite the various myths surrounding the origin of coffee, its history, and its development, scientists traced the origin of the plant back to Yemen. It is believed that coffee was first discovered in Yemen in Mocha.",
      "## Coffee Origin and Spread:",
      "Coffee began in the Arab countries and in Yemen, in the Sufi monasteries, where it helped them wake up at night for worship. The Arabs monopolized its trade, and coffee was not originally roasted, but it was roasted and exported so that it could not be grown after roasting, and the idea was monopolistic in trade.",
      "Coffee spread during the Ottoman Empire with geographic expansion and reached Greece, Malta, Italy, Spain, Germany, Turkey, and other countries around the world, where 2 billion cups of coffee are consumed daily worldwide.",
      "At the beginning of the spread of coffee and its transfer from Yemen to neighboring countries after people tried coffee and gathered around it, and the opening of cafes, several fatwas were issued prohibiting coffee at that time due to their ignorance of this drink, as they believed that it was one of the types of alcoholic beverages, where the name of coffee is derived from wine -qiha- means appetite suppressant in the language.",
      "But after doctors confirmed its effectiveness, it was allowed, and coffee has evolved since then and has become one of the symbols of generosity and chivalry.",
      "## Coffee in Arab Countries:",
      "Coffee is considered an integral part of the culture of Arab countries, and it is a common drink that symbolizes generosity and chivalry. Coffee came to Arab countries, but the types of coffee, extraction methods, and preparation methods varied. Al-Jahli coffee is famous in Kuwait, Turkish coffee in the Levant, as well as Saudi coffee, which is spread in Bahrain, the Emirates, and Saudi Arabia, and Sudanese coffee, which is rich in a unique taste and served in small cups called “Jaak,” where it is one of the symbols of Sudanese hospitality.",
      "Coffee has spread and is grown in more than 70 countries worldwide, with different types, flavors, and diverse roasting and preparation methods, and it has become a favorite and essential drink in most cultures and civilizations.",
      "## Cafes and the Origin of Coffee:",
      "After the spread of coffee, trade began, and cafes were opened in Arab countries, where men gather around them, play chess, and exchange small talk. The custom then expanded to all of Europe, which greatly contributed to spreading coffee and its culture and delivering it to the Americas. Each country that received coffee developed it and presented it in its own way until each culture had its own unique coffee.",
    ],
  },
  {
    slug: "sweetening",
    img: "/brand/blog/sweetening.jpg",
    kicker: "على مزاجك",
    kickerEn: "To Your Taste",
    title: "طرق تحلية القهوة",
    titleEn: "Coffee Sweetening Methods",
    parts: [
      "## ما معنى تحليّة القهوة؟",
      "تحلية القهوة هي عملية إضافة سكر أو محليات أخرى إلى القهوة لتخفيف مرارتها وجعلها أكثر لذة في الشرب. وقد تم تحلية القهوة منذ فترة طويلة، وتختلف طرق التحلية باختلاف المناطق والثقافات.",
      "على الرغم من أن تحلية القهوة بالسكر تعد الطريقة الأكثر شيوعاً لتحلية القهوة، إلا أنه يمكن استخدام العديد من المحليات الأخرى، مثل العسل، أو السكر البني، أو السكر الممزوج بالقرفة. ويمكن أيضاً استخدام الحليب أو القشدة الطازجة لتحلية القهوة.",
      "من الجدير بالذكر أن تحلية القهوة بالسكر يمكن أن يؤدي إلى زيادة مستويات السكر في الدم، ويمكن أن يتسبب في العديد من المشاكل الصحية، مثل السمنة والسكري. لذلك، ينصح بتحلية القهوة بمحليات بديلة، مثل الستيفيا، التي لا تسبب زيادة في مستويات السكر في الدم.",
      "وبالإضافة إلى ذلك، يمكن استخدام القهوة المحلاة بشكل صحيح كجزء من نظام غذائي صحي، حيث يمكن تناولها بشكل معتدل خلال اليوم، وتجنب تناولها بشكل مفرط.",
      "## تحلية القهوة: طرق مختلفة لتحليّة القهوة.",
      "بالإضافة إلى تحلية القهوة بالسكر والمحليات البديلة، هناك العديد من الخيارات الأخرى المتاحة لتحلية القهوة وتعزيز طعمها. من بين هذه الخيارات:",
      "- التحلية بالفانيلا: يمكن إضافة مسحوق الفانيلا إلى القهوة لإضفاء نكهة حلوة ومميزة. كما يمكن استخدام مستخلص الفانيلا لتحلية القهوة بطريقة أكثر رفاهية.",
      "- التحلية بالحليب المكثف: يمكن إضافة الحليب المكثف إلى القهوة لإضفاء نكهة حلوة وكريمية. يمكن أيضاً استخدام الحليب العادي أو الحليب النباتي لتحلية القهوة.",
      "- التحلية بالشوكولاتة: يمكن إضافة مسحوق الشوكولاتة إلى القهوة لإضفاء نكهة حلوة وشوكولاتية. كما يمكن استخدام شرائح الشوكولاتة الداكنة أو الحلوة لتحلية القهوة.",
      "- التحلية بالقرفة: يمكن إضافة مسحوق القرفة إلى القهوة لإضفاء نكهة حلوة وتوابلية. كما يمكن استخدام قضبان القرفة لتحلية القهوة.",
      "- التحلية بالعسل: يمكن استخدام العسل كبديل للسكر لتحلية القهوة بطريقة صحية وطبيعية. يمكن استخدام العسل الأصلي أو العسل المختلط بالفانيلا أو القرفة.",
      "علاوة على ذلك، يمكن استخدام العديد من الخيارات الأخرى لتحلية القهوة، مثل السكر البني، والسكر الممزوج بالقرفة، وحليب جوز الهند، والشيرة، والشراب الحلو، وغيرها.",
      "## بهارات القهوة في البلدان العربية:",
      "كما أن للبلدان الغربية طرقها في شرب القهوة المرة أو بالمحليات، كذلك في البلدان العربية تنتشر ثقافة القهوة المخلوطة التي لا تقدم كقهوة سادة، بل يضاف إيها الزعفران والهيل والقرفة كبهارات تعطيها رائحة زكية وطعم متميز، مثل القهوة التركية يضاف إليها القرنفل والقرفة بالإضافة للسكر، والقهوة السودانية تقدم مع الزنجبيل والزعفران، أما القهوة المغربية تتميز بنكهاتها العطرية، والقهوة السعودية تتميز برائحة الهيل والزعفران.",
      "حتى تطورت بعض الشركات في تقديم أظرف مختلفة للبن مخلوطة بنكهات متعددة منها مُحلّيات للقهوة ومنها بهارات تمنحها عبق زكي وطعم شهي",
      "## أخيرًا:",
      "وبشكل عام، يمكن القول إن تحلية القهوة هي عملية شخصية تعتمد على ذوق الشخص. وباستخدام الخيارات المتاحة، يمكن تحلية القهوة بطريقة تناسب الأذواق المختلفة. ومع اختيار الخيارات الصحية والطبيعية، يمكن تحلية القهوة بطريقة صحية ومفيدة للصحة.",
      "وفي النهاية، يمكن القول إن تحلية القهوة هي عملية مهمة في جعل القهوة أكثر لذة في الشرب، ويمكن الاستمتاع بها بشكل صحي ومعتدل. لذا، لا تتردد في تجربة مختلف الخيارات المتاحة واختيار الأفضل لذوقك الشخصي.",
    ],
    partsEn: [
      "## What is coffee sweetening?",
      "Sweetening coffee is the process of adding sugar or other sweeteners to coffee to reduce its bitterness and make it more enjoyable to drink. Coffee has been sweetened for a long time, and sweetening methods vary depending on the region and culture.",
      "Although sweetening coffee with sugar is the most common way to sweeten coffee, many other sweeteners can be used, such as honey, brown sugar, or sugar mixed with cinnamon. Milk or fresh cream can also be used to sweeten coffee.",
      "It is worth noting that sweetening coffee with sugar can lead to an increase in blood sugar levels and can cause many health problems, such as obesity and diabetes. Therefore, it is recommended to sweeten coffee with alternative sweeteners, such as stevia, which does not increase blood sugar levels.",
      "In addition, sweetened coffee can be used as part of a healthy diet, where it can be consumed moderately during the day and avoiding excessive consumption.",
      "## Different methods to sweeten coffee:",
      "In addition to sweetening coffee with sugar and alternative sweeteners, there are many other options available to sweeten coffee and enhance its taste. Among these options:",
      "- Vanilla sweetening: Vanilla powder can be added to coffee to give it a sweet and distinctive flavor. Vanilla extract can also be used to sweeten coffee in a more luxurious way.",
      "- Condensed milk sweetening: Condensed milk can be added to coffee to give it a sweet and creamy flavor. Regular milk or plant-based milk can also be used to sweeten coffee.",
      "- Chocolate sweetening: Chocolate powder can be added to coffee to give it a sweet and chocolaty flavor. Dark or sweet chocolate slices can also be used to sweeten coffee.",
      "- Cinnamon sweetening: Cinnamon powder can be added to coffee to give it a sweet and spicy flavor. Cinnamon sticks can also be used to sweeten coffee.",
      "- Honey sweetening: Honey can be used as a natural and healthy sugar substitute to sweeten coffee. Raw honey or honey mixed with vanilla or cinnamon can be used.",
      "In addition, many other options can be used to sweeten coffee, such as brown sugar, sugar mixed with cinnamon, coconut milk, syrup, sweet drinks, and others.",
      "## Coffee spices in Arab countries:",
      "Just as Western countries have their ways of drinking plain or sweetened coffee, the culture of mixed coffee is widespread in Arab countries, which is not served as plain coffee, but saffron, cardamom, and cinnamon are added as spices, giving it a distinct aroma and flavor. For example, Turkish coffee is served with cloves, cinnamon, and sugar, Sudanese coffee is served with ginger and saffron, Moroccan coffee is known for its aromatic flavors, and Saudi coffee is known for its cardamom and saffron aroma.",
      "## Finally:",
      "In general, sweetening coffee is a personal process that depends on the individual's taste. By using the available options, coffee can be sweetened in a way that suits different tastes. With the choice of healthy and natural options, coffee can be sweetened in a healthy and beneficial way for health.",
      "In conclusion, sweetening coffee is an important process in making it more enjoyable to drink, and it can be enjoyed in a healthy and moderate way. So, do not hesitate to try different available options and choose the best for your personal taste.",
    ],
  },
  {
    slug: "espresso",
    img: "/brand/blog/espresso.jpg",
    kicker: "حكاية البن",
    kickerEn: "The Bean Story",
    title: "قهوة الإيسبريسو: إسهامات إيطاليا في تغيير مفهوم القهوة.",
    titleEn: "Espresso Coffee: Italy's Contribution to Changing the Concept of Coffee",
    parts: [
      "## أصل قهوة الايسبريسو:",
      "سُميت قهوة الايسبريسو بما يعني (اكسبريس) باللغة الإيطالية – أي سريعة التحضير- وهي عبارة عن ضغط البن المطحون واستخلاص الماء من خلاله، ولم يتم تحديد مخترع الايسبريسو حتى الآن، ولكنها بدأت من إيطاليا وتطورت على مر العصور",
      "حيث تم اختراع مكينه لصنع قهوة الإسبريسو على يد الإيطالي أنجلو موريوندو في عام 1884، ثم بعد ذلك قدم لويجي بيزيرا العديد من التحسينات التي تساعد بتسريع عملية إنتاج القهوة وتطوير المكينة.",
      "ومن هنا تم افتتاح أول مصنع لتصنيع قهوة الإسبريسو في ميلانو الواقعة في إيطاليا ومن بين هذه الشركات (La Pavoni) لا بافونا، انتجت أول مكينة ايسبريسو في العالم عام ١٩٠٥.",
      "## قهوة الإسبريسو مع الحليب:",
      "### متى تمت إضافة الحليب للقهوة لأول مرة؟",
      "لم يُحدد بدقة حتى الآن، ولكن يُعتقد أنه تم إضافة الحليب لقهوة الإسبريسو في القرن السابع عشر في إيطاليا، كما أن إيطاليا أول من ابتكر فكرة إضافة للحليب لقهوة الإسبريسو وبمرور الوقت تطورت في عدة بلدان، وفي بعض البلدان أصبحت المشروب الرسمي ضمن ثقافتهم.",
      "ويشاع شرب الكابتشينو في إيطاليا.",
      "## مشروبات الإسبريسو بالحليب:",
      "يعتبر الاسبريسو بالحليب (Espresso with Milk) واحداً من المشروبات الأساسية في عالم القهوة، وهو يتكون من قهوة إسبريسو مع إضافة حليب معالج بخاصية التبخير. ويتم تحضيره عادةً باستخدام آلة إسبريسو، التي تستخدم ضغطاً عالياً لاستخلاص القهوة بسرعة.",
      "ومن بين الأنواع الشائعة للإسبريسو بالحليب:",
      "- الكابتشينو (Cappuccino)، وهو مشروب قهوة إسبريسو مع حليب مجهز بخاصية التبخير ورغوة الحليب.",
      "- اللاتيه (Latte)، وهو مشروب قهوة إسبريسو مع حليب مجهز بخاصية التبخير وقليل من رغوة الحليب.",
      "- الموكا (Mocha)، وهو مشروب يتكون من قهوة إسبريسو وشراب الشوكولاتة وحليب مجهز بخاصية التبخير.",
      "## تأثير قهوة الإسبريسو على الثقافة المجتمعية:",
      "تحتل قهوة الإسبريسو مكانة مهمة في الثقافة المجتمعية في العديد من البلدان، وتعكس طريقة حياة وتقاليد المجتمعات التي تستهلكها. وبالتالي، يمكن أن تؤثر قهوة الإسبريسو على تغيير سلوك المجتمع وتأثيره على الحياة الاجتماعية والثقافية.",
      "في إيطاليا، على سبيل المثال، بعد ابتكار الإسبريسو اصبحت تشكل قهوة الإسبريسو جزءًا أساسيًا من الثقافة المحلية، وتعتبر رمزًا للحضارة والتطور وتمثل طريقة للتواصل وتبادل الأفكار والأخبار بين الناس. وتحتل مقاهي الإسبريسو مكانة مهمة في حياة المجتمع الإيطالي، حيث يقوم الناس بزيارتها للاستمتاع بكوب من الإسبريسو والتحدث مع الأصدقاء والزملاء، وبسبب السياحة في إيطاليا انتشرت هذه الثقافة حول العالم.",
      "وفي الولايات المتحدة، يمكن القول إن قهوة الإسبريسو أصبحت رمزاً لثقافة العمل والإنتاجية، حيث يستخدمها الكثيرون لزيادة الطاقة والتركيز في العمل. ويعتبر تناول قهوة الإسبريسو في بعض المجتمعات الأمريكية علامة على الرقي والثقافة العالية.",
      "بالإضافة إلى ذلك، يمكن أن تؤثر قهوة الإسبريسو على السلوك الاجتماعي والثقافي من خلال تأثيرها على الصحة العامة والتواصل الاجتماعي. وقد أظهرت الدراسات أن تناول قهوة الإسبريسو بشكل معتدل قد يساهم في تحسين المزاج والتركيز والأداء الذهني، مما يمكن أن يؤثر على السلوك الاجتماعي والتدريب والتعلم.",
      "وبشكل عام، يمكن القول إن قهوة الإسبريسو تعكس الثقافة المجتمعية في العديد من البلدان، ويمكنها أن تؤثر على السلوك الاجتماعي.",
    ],
    partsEn: [
      "## The origin of espresso coffee:",
      "Espresso coffee, which means “fast” in Italian, is made by compressing ground coffee and extracting water through it. The inventor of espresso has not been definitively identified, but it began in Italy and evolved over time. Angelo Moriondo, an Italian, invented a machine for making espresso in 1884, and Luigi Bezzera later introduced many improvements that helped speed up the coffee-making process and develop the machine. The first factory for manufacturing espresso coffee was opened in Milan, Italy, and among these companies was La Pavoni, which produced the world's first espresso machine in 1905.",
      "## Espresso coffee with milk:",
      "### When was milk first added to coffee?",
      "It has not been definitively determined, but it is believed that milk was first added to espresso coffee in the 17th century in Italy. Italy was also the first to come up with the idea of adding milk to espresso coffee, and over time it developed in several countries, becoming the official drink in some cultures. Cappuccino is widespread in Italy.",
      "## Espresso drinks with milk:",
      "Espresso with milk (Espresso with Milk) is considered one of the basic drinks in the world of coffee, consisting of espresso coffee with steamed and frothed milk. It is usually prepared using an espresso machine, which uses high pressure to extract coffee quickly.",
      "Among the common types of espresso with milk are:",
      "- Cappuccino, which is a drink of espresso coffee with steamed and frothed milk.",
      "- Latte, which is a drink of espresso coffee with steamed milk and a little foam.",
      "- Mocha, which is a drink made from espresso coffee, chocolate syrup, and steamed milk.",
      "## The impact of espresso coffee on societal culture:",
      "Espresso coffee occupies an important place in the societal culture of many countries, reflecting the way of life and traditions of the communities that consume it. Therefore, espresso coffee can influence changes in societal behavior and its impact on social and cultural life.",
      "In Italy, for example, after the invention of espresso, espresso coffee became an essential part of local culture, a symbol of civilization and development, and a means of communication and exchange of ideas and news among people. Espresso cafes occupy an important place in Italian society, where people visit them to enjoy a cup of espresso and talk with friends and colleagues. Due to tourism in Italy, this culture has spread around the world.",
      "In the United States, espresso coffee can be said to have become a symbol of work and productivity, as many people use it to increase energy and focus at work. Drinking espresso coffee in some American societies is considered a sign of sophistication and high culture.",
      "In addition, espresso coffee can influence social and cultural behavior through its impact on public health and social communication. Studies have shown that moderate consumption of espresso coffee may contribute to improving mood, concentration, and mental performance, which can affect social behavior, training, and learning.",
      "In general, espresso coffee reflects societal culture in many countries and can influence societal behavior.",
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
