/**
 * GENERATED by scripts/geocode-branches.mjs — do not hand-edit casually.
 *
 * APPROXIMATE coordinates from OpenStreetMap Nominatim. They resolve the
 * street or district in each address, not the shop unit, so a pin may sit
 * some way from the actual door. Accurate enough to rank branches by
 * distance and orient a map; NOT survey data.
 *
 * `quality` records how the match was obtained:
 *   "district" — resolved to the branch district (usable for proximity)
 *   "city"     — only the city centroid was found. Several branches will
 *                share these coordinates, so proximity ranking between
 *                them is meaningless. Replace these first.
 *
 * Replace any entry with exact values when you have them.
 */

export interface BranchCoords {
  lat: number;
  lng: number;
  quality: "district" | "city" | "exact";
}

export const branchCoords: Record<string, BranchCoords> = {
  "sulaimaniyah": { lat: 21.506182, lng: 39.2487, quality: "district" }, // As Sulimaniyah, Jeddah, Governorate of Jidda, Makkah Region, 22253, Saudi Arabia
  "rahili-makkah-road": { lat: 21.5504432, lng: 39.1742363, quality: "city" }, // city centroid
  "jamiaa": { lat: 21.475115, lng: 39.251018, quality: "district" }, // Al Jamiah, Jeddah, Governorate of Jidda, Makkah Region, Saudi Arabia
  "rabwah": { lat: 21.601098, lng: 39.181967, quality: "district" }, // Al-Rabwah, Jeddah, Governorate of Jidda, Makkah Region, 23448, Saudi Arabia
  "quraish": { lat: 21.595717, lng: 39.152687, quality: "district" }, // Quraish Street, Al-Salamah, Jeddah, Governorate of Jidda, Makkah Region, 23524, Saudi Arab
  "hamdaniyah": { lat: 21.774172, lng: 39.175786, quality: "district" }, // Leader express ليدر اكسبرس الحمدانية جدة, Al Harameen Road, Al Hamdaniyah, Jeddah, Governo
  "halqa": { lat: 21.565913, lng: 39.221733, quality: "district" }, // Um Al Qura Street, Al-Rehab, Jeddah, Governorate of Jidda, Makkah Region, 23345, Saudi Ara
  "dhahban": { lat: 21.931012, lng: 39.118174, quality: "district" }, // Dhahban, Governorate of Jidda, Makkah Region, Saudi Arabia
  "kabri-al-muraba": { lat: 21.564569, lng: 39.17081, quality: "district" }, // كبري المربع, Al-Madinah Al-Munawwarah Road, Al Faisaliyyah, Jeddah, Governorate of Jidda, 
  "tahlia-mall": { lat: 21.5504432, lng: 39.1742363, quality: "city" }, // city centroid
  "corniche": { lat: 21.559269, lng: 39.11207, quality: "district" }, // طريق الكورنيش الفرعي, Al-Shatee, Jeddah, Governorate of Jidda, Makkah Region, 23422, Saudi
  "abhor": { lat: 21.807046, lng: 39.086079, quality: "district" }, // Obhor, Governorate of Jidda, Makkah Region, Saudi Arabia
  "rayan": { lat: 21.57838, lng: 39.156928, quality: "district" }, // الريان للمعسلات, Sari Road, Al-Rawdah, Jeddah, Governorate of Jidda, Makkah Region, 23436,
  "taysir": { lat: 21.539277, lng: 39.296737, quality: "district" }, // التيسير, Palestine Road, Mraykh, Jeddah, Governorate of Jidda, Makkah Region, 23366, Saudi
  "zaidi": { lat: 21.417993, lng: 39.707813, quality: "district" }, // قاعة ليلة بدر الزايدي للإحتفالات, Old Mecca Road, Umm Al Jud, الشميسي, Makkah Al Mukarrama
  "kokayyah": { lat: 21.377638, lng: 39.812789, quality: "district" }, // Al Kakiyah, Makkah Al Mukarramah, Makkah Region, Saudi Arabia
  "shawqiyyah": { lat: 21.387172, lng: 39.796527, quality: "district" }, // Ash Shawqiyah, Makkah Al Mukarramah, Makkah Region, 24351, Saudi Arabia
  "juranah": { lat: 21.560399, lng: 39.956588, quality: "district" }, // Al Juranah, Makkah Al Mukarramah, Makkah Region, Saudi Arabia
  "jumum": { lat: 21.634315, lng: 39.674535, quality: "district" }, // حديقة حي السلام, -, Al Jumum, Makkah Region, 25351, Saudi Arabia
  "bahrah-1": { lat: 21.401272, lng: 39.45001, quality: "district" }, // Bahrah, Makkah Region, Saudi Arabia
  "sharai": { lat: 21.481496, lng: 39.981999, quality: "district" }, // Ar Rashidiyyah, Ash Sharai, Makkah Al Mukarramah, Makkah Region, Saudi Arabia
  "khadra": { lat: 21.467239, lng: 39.915442, quality: "district" }, // Al Khadraa, Makkah Al Mukarramah, Makkah Region, Saudi Arabia
  "nawaria": { lat: 21.55811, lng: 39.767212, quality: "district" }, // Al Nawariyah, Makkah Al Mukarramah, Makkah Region, 24215, Saudi Arabia
  "areeshi": { lat: 21.32728, lng: 40.02736, quality: "district" }, // SASCO, طريق الكرا الهدا, Brm, ريع وصيق وفقاسة نعمان, Makkah Al Mukarramah, Makkah Region, 
  "nuzha": { lat: 21.428115, lng: 39.801089, quality: "district" }, // Az Zahra, Makkah Al Mukarramah, Makkah Region, 24221, Saudi Arabia
  "bohairat": { lat: 21.490519, lng: 39.777741, quality: "district" }, // Al Buhayrat, Makkah Al Mukarramah, Makkah Region, Saudi Arabia
  "umrah": { lat: 21.56883, lng: 39.788011, quality: "district" }, // Al Umrah, Al Jumum, Makkah Region, Saudi Arabia
  "bahrah-2": { lat: 21.401272, lng: 39.45001, quality: "district" }, // Bahrah, Makkah Region, Saudi Arabia
  "husainiyyah": { lat: 21.31869, lng: 39.878991, quality: "district" }, // Al Husayniyah, Makkah Al Mukarramah, Makkah Region, 24372, Saudi Arabia
  "sharai-rashidiyyah": { lat: 21.420847, lng: 39.826869, quality: "city" }, // city centroid
  "hara": { lat: 21.456854, lng: 39.868454, quality: "district" }, // Hira Cultural District, Makkah Al Mukarramah, Makkah Region, Saudi Arabia
  "hada": { lat: 21.368611, lng: 40.284722, quality: "district" }, // Al Hada, Al Taif, Makkah Region, Saudi Arabia
  "um-al-jood": { lat: 21.415838, lng: 39.717636, quality: "district" }, // Umm Al Jud, Makkah Al Mukarramah, Makkah Region, 24323, Saudi Arabia
  "muzdalifah": { lat: 21.386346, lng: 39.915147, quality: "district" }, // Al Muzdalifah, Makkah Al Mukarramah, Makkah Region, 24251, Saudi Arabia
  "wessam-1": { lat: 21.2702801, lng: 40.4158308, quality: "city" }, // city centroid
  "jadiyyah": { lat: 21.2702801, lng: 40.4158308, quality: "city" }, // city centroid
  "sil": { lat: 21.379539, lng: 40.438177, quality: "district" }, // Al Sayl Road, Al Qayam Al Asfal, At Ta'if, Al Taif, Makkah Region, Saudi Arabia
};
